### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by warrenguerin** [Tendrl/ui#984]
Failure in Job b64a5c61-a5bd-4255-8b83-7dfc223f8054 Flow tendrl.flows.ImportCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 242, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 124, in run raise ex AtomExecutionFailedError: Atom Execution failed. Error: Node doesnt have network details populated

--

my issue is I cant unmanage and I cant re-import, how can I figure out what the actual issue is and fix it?

My config looks correct with the FQDN's.

--

Second question is, I am running tendrl on one of the file servers, is this my actual problem?

Thank you

**Comment by gnehapk** [comment]
@nthomas-redhat @shtripat @GowthamShanmugam can you please have a look

**Comment by GowthamShanmugam** [comment]
This issue happens when we fire import flow before all the nodes are listed, please wait for all the nodes are shown in detected cluster page and then fire import

**Comment by warrenguerin** [comment]
2 hosts showing

![image](https://user-images.githubusercontent.com/39998900/41351029-033b5eb6-6f0d-11e8-86a9-124c5c75d6d1.png)

import is greyd out 

![image](https://user-images.githubusercontent.com/39998900/41351053-126b22a4-6f0d-11e8-983d-b36bd01a40ad.png)

attempting to unmanage says starting task, but nothing happens

**Comment by mbukatov** [comment]
@Tendrl/qe

**Comment by warrenguerin** [comment]
Still not winning on this after deleting everything and starting over, to note that this is an existing cluster managed by Heketi.

My new PRD cluster, also managed by Heketi has imported fine.

I cant figure out where its getting this information from:

![image](https://user-images.githubusercontent.com/39998900/41433529-2829f0e8-7011-11e8-91eb-73172455506e.png)

any help on this would be appreciated.

**Comment by GowthamShanmugam** [comment]
deleting means you have deleted everything including etcd and removed all tendrl components also?

**Comment by warrenguerin** [comment]
Correct, pretty much a start from scratch.
Could it be that this cluster is managed by Heketi currently?

**Comment by GowthamShanmugam** [comment]
@r0h4n do you have any suggestion about this problem, do you thing heketi will affect tendrl

**Comment by r0h4n** [comment]
Tendrl has not been tested with heketi + gluster environments , we can start documenting some expectations around this environment and then begin initial testing
